FileController to upload user's private files.
bezelix/RecruitmentAppBackend pull request #20
Opened 2021-09-16 12:54 UTC by bezelix

- I added a FileController responsible for uploading user's private files. Controller requires authorization

- I also added ASP.NET Core static files middleware. Includes middleware for serving static files, directory browsing, and default files.
- To make the api more efficient I used Response Cache for downloaded private files.

2021-09-20 14:53 UTC, Ballkar requested changes

2021-09-20 14:53 UTC, Ballkar commented on RecruitmentApp/Controllers/FileController.cs
> +                var path = $"{rootPath}/PrivateFiles/{_userContextService.GetUserId}";
widze że to się powiela(widziałem w innym miejscu). 

Zrób sobie jakiś serwis albo klasę al'a helper czy util(może statyczna?). Która Ci zwróci tą ścięzkę jak jej podasz id usera

2021-09-20 14:53 UTC, Ballkar commented on RecruitmentApp/Controllers/FileController.cs
> +            if (file != null && file.Length > 0)
chyba czytelniej będziesz miał jak zrobisz
if (file != null && file.Length > 0) {
            return BadRequest();
}
.
.
.
reszta kodu.


Bo nie masz tak zagnieżdżonego kodu w tym ifie

2021-09-20 14:53 UTC, Ballkar commented on RecruitmentApp/PrivateFiles/6/cv.txt
> +- Wszystkie postacie w grze stworzyłem za pomocą programu Fuse trzymając się własnej koncepcji fabularnej.
co to jest?

2021-09-20 14:53 UTC, Ballkar commented on RecruitmentApp/wwwroot/TextFile.txt
> +﻿this is a sample file.
chyba do wyrzucenia

2021-09-20 16:11 UTC, bezelix commented on RecruitmentApp/PrivateFiles/6/cv.txt
> +- Wszystkie postacie w grze stworzyłem za pomocą programu Fuse trzymając się własnej koncepcji fabularnej.
pllik który testowo wgrywałem do testów

2021-09-21 05:50 UTC, Ballkar requested changes
ostatnia poprawka i możesz mergować

2021-09-21 05:50 UTC, Ballkar commented on RecruitmentApp/Controllers/FileController.cs
> +            {
bez tego ifa, teraz jest tak samo jak było tylko w odwrotnej kolejności :D

return przerwie Ci kod, więc ten else jest zupełnie zbędny. tak samo jak poniżej masz kod 
`if (resume is null)
                    throw new NotFoundException("Resume not found");`

2021-09-27 13:40 UTC, Ballkar approved these changes

2021-09-27 13:47 UTC, merged